// Generated by `pnpm db:types`. Do not hand-edit — regenerate after every migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.15'
  }
  public: {
    Tables: {
      doc_image_sweep_log: {
        Row: {
          byte_size: number | null
          doc_image_id: string
          full_path: string
          id: number
          node_id: string | null
          orphaned_at: string | null
          storage_path: string
          swept_at: string
        }
        Insert: {
          byte_size?: number | null
          doc_image_id: string
          full_path: string
          id?: never
          node_id?: string | null
          orphaned_at?: string | null
          storage_path: string
          swept_at?: string
        }
        Update: {
          byte_size?: number | null
          doc_image_id?: string
          full_path?: string
          id?: never
          node_id?: string | null
          orphaned_at?: string | null
          storage_path?: string
          swept_at?: string
        }
        Relationships: []
      }
      doc_images: {
        Row: {
          alt_text: string | null
          byte_size: number
          created_at: string
          full_path: string
          height: number
          id: string
          node_id: string
          orphaned_at: string | null
          storage_path: string
          uploaded_by: string | null
          width: number
        }
        Insert: {
          alt_text?: string | null
          byte_size: number
          created_at?: string
          full_path: string
          height: number
          id?: string
          node_id: string
          orphaned_at?: string | null
          storage_path: string
          uploaded_by?: string | null
          width: number
        }
        Update: {
          alt_text?: string | null
          byte_size?: number
          created_at?: string
          full_path?: string
          height?: number
          id?: string
          node_id?: string
          orphaned_at?: string | null
          storage_path?: string
          uploaded_by?: string | null
          width?: number
        }
        Relationships: [
          {
            foreignKeyName: 'doc_images_node_id_fkey'
            columns: ['node_id']
            isOneToOne: false
            referencedRelation: 'doc_nodes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'doc_images_uploaded_by_fkey'
            columns: ['uploaded_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      doc_nodes: {
        Row: {
          archived_at: string | null
          author_id: string | null
          content_md: string | null
          created_at: string
          depth: number
          difficulty: number | null
          id: string
          kind: Database['public']['Enums']['doc_kind']
          last_edited_by: string | null
          origin: Database['public']['Enums']['doc_origin']
          parent_id: string | null
          position: number
          published_at: string | null
          search_vector: unknown
          slug: string
          status: Database['public']['Enums']['doc_status']
          title: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          author_id?: string | null
          content_md?: string | null
          created_at?: string
          depth?: number
          difficulty?: number | null
          id?: string
          kind?: Database['public']['Enums']['doc_kind']
          last_edited_by?: string | null
          origin?: Database['public']['Enums']['doc_origin']
          parent_id?: string | null
          position?: number
          published_at?: string | null
          search_vector?: unknown
          slug: string
          status?: Database['public']['Enums']['doc_status']
          title: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          author_id?: string | null
          content_md?: string | null
          created_at?: string
          depth?: number
          difficulty?: number | null
          id?: string
          kind?: Database['public']['Enums']['doc_kind']
          last_edited_by?: string | null
          origin?: Database['public']['Enums']['doc_origin']
          parent_id?: string | null
          position?: number
          published_at?: string | null
          search_vector?: unknown
          slug?: string
          status?: Database['public']['Enums']['doc_status']
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'doc_nodes_author_id_fkey'
            columns: ['author_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'doc_nodes_last_edited_by_fkey'
            columns: ['last_edited_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'doc_nodes_parent_id_fkey'
            columns: ['parent_id']
            isOneToOne: false
            referencedRelation: 'doc_nodes'
            referencedColumns: ['id']
          },
        ]
      }
      doc_tags: {
        Row: {
          node_id: string
          tag_id: string
        }
        Insert: {
          node_id: string
          tag_id: string
        }
        Update: {
          node_id?: string
          tag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'doc_tags_node_id_fkey'
            columns: ['node_id']
            isOneToOne: false
            referencedRelation: 'doc_nodes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'doc_tags_tag_id_fkey'
            columns: ['tag_id']
            isOneToOne: false
            referencedRelation: 'tags'
            referencedColumns: ['id']
          },
        ]
      }
      doc_versions: {
        Row: {
          content_md: string | null
          created_at: string
          edited_by: string | null
          id: string
          node_id: string
          title: string
        }
        Insert: {
          content_md?: string | null
          created_at?: string
          edited_by?: string | null
          id?: string
          node_id: string
          title: string
        }
        Update: {
          content_md?: string | null
          created_at?: string
          edited_by?: string | null
          id?: string
          node_id?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: 'doc_versions_edited_by_fkey'
            columns: ['edited_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'doc_versions_node_id_fkey'
            columns: ['node_id']
            isOneToOne: false
            referencedRelation: 'doc_nodes'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string
          id: string
          is_active: boolean
          role: Database['public']['Enums']['user_role']
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name: string
          id: string
          is_active?: boolean
          role?: Database['public']['Enums']['user_role']
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string
          id?: string
          is_active?: boolean
          role?: Database['public']['Enums']['user_role']
          updated_at?: string
        }
        Relationships: []
      }
      tags: {
        Row: {
          id: string
          name: string
          slug: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_role: {
        Args: never
        Returns: Database['public']['Enums']['user_role']
      }
      custom_access_token_hook: { Args: { event: Json }; Returns: Json }
      extract_image_paths: { Args: { content: string }; Returns: string[] }
      get_doc_node_image_paths: {
        Args: { target_node_id: string }
        Returns: {
          full_path: string
          storage_path: string
        }[]
      }
      get_doc_tree: {
        Args: never
        Returns: {
          depth: number
          id: string
          kind: Database['public']['Enums']['doc_kind']
          parent_id: string
          path: string[]
          position: number
          slug: string
          status: Database['public']['Enums']['doc_status']
          title: string
        }[]
      }
      get_orphan_sweep_candidates: {
        Args: never
        Returns: {
          alt_text: string | null
          byte_size: number
          created_at: string
          full_path: string
          height: number
          id: string
          node_id: string
          orphaned_at: string | null
          storage_path: string
          uploaded_by: string | null
          width: number
        }[]
        SetofOptions: {
          from: '*'
          to: 'doc_images'
          isOneToOne: false
          isSetofReturn: true
        }
      }
      is_admin: { Args: never; Returns: boolean }
      is_editor: { Args: never; Returns: boolean }
    }
    Enums: {
      doc_kind: 'section' | 'page'
      doc_origin: 'team' | 'course' | 'generated'
      doc_status: 'draft' | 'needs_review' | 'published'
      user_role: 'admin' | 'editor' | 'member'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      doc_kind: ['section', 'page'],
      doc_origin: ['team', 'course', 'generated'],
      doc_status: ['draft', 'needs_review', 'published'],
      user_role: ['admin', 'editor', 'member'],
    },
  },
} as const
